# THIS IS OLD WAY

#[masters]
#osmaster.okd.local ansible_host=192.168.5.72

#[workers]
#okd-worker01.okd.local ansible_host=192.168.5.84


[masters]
osmaster.okd.local ansible_host=192.168.5.72

[workers]
okd-worker01.okd.local ansible_host=192.168.5.84

[okd_cluster:children]
masters
workers

[okd_cluster:vars]
ansible_user=root
