---
- name: parcticing block and line in file module
  hosts: okd_cluster
  become: yes
  gather_facts: yes


  tasks:


  - name: inline practice
    lineinfile:
      path: /tmp/config-practice/app.conf
      regexp: 'NODE NAME = '
      line: 'Node Name = {{ inventory_hostname }}'
#      state: present
      backup: yes


  - name: blockinfile practice
    blockinfile:
      path: /tmp/config-practice/app.conf
      marker: "# {mark} LAB Block Practice"
      block: |
        this is added as part of block 3
        this is added as part of block 4
      backup: no  
   
