---
- name: Create seperate based on master or worker node
  hosts: okd_cluster
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Create directory for each node
      file:
        path: /tmp/role-based-check
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Install package for master nodes
      yum:
        name: tree
        state: present
      when: "'masters' in group_names"  
    
    - name: Install package for workers nodes
      yum:
        name: wget
        state: present
      when: "'workers' in group_names"
      
    - name: Create a file for master nodes
      copy:
        dest: /tmp/role-based-check/role-info.txt
        content: "This is a Master node {{ inventory_hostname }} with IP {{ ansible_default_ipv4.address }}\n"
        owner: root
        group: root
        mode: '0644'
      when: "'masters' in group_names" 


    - name: Create a file for worker nodes
      copy:
        dest: /tmp/role-based-check/role-info.txt
        content: "This is a Worker node {{ inventory_hostname }} with IP {{ ansible_default_ipv4.address }}\n"
        owner: root
        group: root
        mode: '0644'
      when: "'workers' in group_names"  