---
- name: Practice Handlers 2
  hosts: okd_cluster
  become: yes
  gather_facts: yes


  tasks:
    - name: Create a handler practice directory
      file:
        path: /tmp/handler_practice
        state: directory
        owner: root
        group root:
        mode: '0755


    - name: create app config file
      copy:
        dest: /tmp/handler_practice/app.conf
        content: |
          Host: {{ inventoery_hostname }}
          IP: {{ anisble_default_ipv4.address }}
          Role: {% if 'masters' in group_names %}MASTER{% else %}WORKER{% endif %}
          owner: root
          group: root
          mode: '0644'
      notify: Record_config_update


    - name: Create helper Script
      copy: 
        dest: /tmp/helper_practice/helper.sh
        content: |
          #!/bin/bash
          echo "hello this is handler parctice
        owner: root
        group: root
        mode: '0755'


  handler:
    - name: Record_config_update
      copy:
        dest: /tmp/handler_practice/config_update.log
        content: |
          Handler ran on {{ inventory_hostname }} becasue of config change
        owner: root
        group: root
        mode: '0644'

