---
- name: Practice Handlers 2
  hosts: okd_cluster
  become: yes
  gather_facts: yes

  tasks:
    - name: Create a handler practice directory
      file:
        path: /tmp/handler_practice2
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create app config file
      copy:
        dest: /tmp/handler_practice/app.conf
        content: |
          HOST: {{ inventory_hostname }}
          IP: {{ ansible_default_ipv4.address }}
          Role: {% if 'masters' in group_names %}MASTER{% else %}WORKER{% endif %}
        owner: root
        group: root
        mode: '0644'
      notify: Record config update


    - name: Create helper Script
      copy: 
        dest: /tmp/helper_practice2/helper.sh
        content: |
          #!/bin/bash
          echo "hello this is handler parctice
        owner: root
        group: root
        mode: '0755'


  handler:
    - name: Records config update
      copy:
        dest: /tmp/handler_practice2/config_update.log
        content: |
          Handler ran on {{ inventory_hostname }} becasue of config change
        owner: root
        group: root
        mode: '0644'

